language: php

php: 7.1

before_script:
    - composer install

    - docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix --show-progress=estimating --verbose .
    - docker run --rm -v $PWD:/app phpqa/security-checker security:check
