language: php

php: 5.6
    
script:
    - docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix --show-progress=estimating --verbose .
    - docker run --rm -v $PWD:/app phpqa/security-checker security:check

notifications:
    email:
        recipients:
            - l.guibert@hotmail.fr
        on_success: never
        on_failure: always
